package hibernate.entity;
// Generated Jul 8, 2020 9:48:47 AM by Hibernate Tools 4.3.1



/**
 * Berita generated by hbm2java
 */
public class Berita  implements java.io.Serializable {


     private int idberita;
     private String waktuberita;
     private String judul;
     private String detail;
     private String sumber;
     private String file;

    public Berita() {
    }

    public Berita(int idberita, String waktuberita, String judul, String detail, String sumber, String file) {
       this.idberita = idberita;
       this.waktuberita = waktuberita;
       this.judul = judul;
       this.detail = detail;
       this.sumber = sumber;
       this.file = file;
    }
   
    public int getIdberita() {
        return this.idberita;
    }
    
    public void setIdberita(int idberita) {
        this.idberita = idberita;
    }
    public String getWaktuberita() {
        return this.waktuberita;
    }
    
    public void setWaktuberita(String waktuberita) {
        this.waktuberita = waktuberita;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public String getSumber() {
        return this.sumber;
    }
    
    public void setSumber(String sumber) {
        this.sumber = sumber;
    }
    public String getFile() {
        return this.file;
    }
    
    public void setFile(String file) {
        this.file = file;
    }




}


