package hibernate.entity;
// Generated Jul 8, 2020 9:48:47 AM by Hibernate Tools 4.3.1



/**
 * Chatbox generated by hbm2java
 */
public class Chatbox  implements java.io.Serializable {


     private int id;
     private String komentar;

    public Chatbox() {
    }

    public Chatbox(int id, String komentar) {
       this.id = id;
       this.komentar = komentar;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getKomentar() {
        return this.komentar;
    }
    
    public void setKomentar(String komentar) {
        this.komentar = komentar;
    }




}


