package hibernate.entity;
// Generated Jul 8, 2020 9:48:47 AM by Hibernate Tools 4.3.1



/**
 * Pengguna generated by hbm2java
 */
public class Pengguna  implements java.io.Serializable {


     private int idpengguna;
     private String nama;
     private String gender;

    public Pengguna() {
    }

    public Pengguna(int idpengguna, String nama, String gender) {
       this.idpengguna = idpengguna;
       this.nama = nama;
       this.gender = gender;
    }
   
    public int getIdpengguna() {
        return this.idpengguna;
    }
    
    public void setIdpengguna(int idpengguna) {
        this.idpengguna = idpengguna;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }




}


