package hibernate.entity;
// Generated Jul 8, 2020 9:48:47 AM by Hibernate Tools 4.3.1



/**
 * Perkembangancovid19 generated by hbm2java
 */
public class Perkembangancovid19  implements java.io.Serializable {


     private int idperubahan;
     private String waktuperubahan;
     private int terkonfirmasi;
     private int dirawat;
     private int sembuh;
     private int meninggal;

    public Perkembangancovid19() {
    }

    public Perkembangancovid19(int idperubahan, String waktuperubahan, int terkonfirmasi, int dirawat, int sembuh, int meninggal) {
       this.idperubahan = idperubahan;
       this.waktuperubahan = waktuperubahan;
       this.terkonfirmasi = terkonfirmasi;
       this.dirawat = dirawat;
       this.sembuh = sembuh;
       this.meninggal = meninggal;
    }
   
    public int getIdperubahan() {
        return this.idperubahan;
    }
    
    public void setIdperubahan(int idperubahan) {
        this.idperubahan = idperubahan;
    }
    public String getWaktuperubahan() {
        return this.waktuperubahan;
    }
    
    public void setWaktuperubahan(String waktuperubahan) {
        this.waktuperubahan = waktuperubahan;
    }
    public int getTerkonfirmasi() {
        return this.terkonfirmasi;
    }
    
    public void setTerkonfirmasi(int terkonfirmasi) {
        this.terkonfirmasi = terkonfirmasi;
    }
    public int getDirawat() {
        return this.dirawat;
    }
    
    public void setDirawat(int dirawat) {
        this.dirawat = dirawat;
    }
    public int getSembuh() {
        return this.sembuh;
    }
    
    public void setSembuh(int sembuh) {
        this.sembuh = sembuh;
    }
    public int getMeninggal() {
        return this.meninggal;
    }
    
    public void setMeninggal(int meninggal) {
        this.meninggal = meninggal;
    }




}


