package hibernate.entity;
// Generated Jul 8, 2020 9:48:47 AM by Hibernate Tools 4.3.1



/**
 * Perkembanganglobal generated by hbm2java
 */
public class Perkembanganglobal  implements java.io.Serializable {


     private int idperubahan2;
     private String waktuperubahan2;
     private int terkonfirmasi2;
     private int sembuh2;
     private int dirawat2;
     private int meninggal2;

    public Perkembanganglobal() {
    }

    public Perkembanganglobal(int idperubahan2, String waktuperubahan2, int terkonfirmasi2, int sembuh2, int dirawat2, int meninggal2) {
       this.idperubahan2 = idperubahan2;
       this.waktuperubahan2 = waktuperubahan2;
       this.terkonfirmasi2 = terkonfirmasi2;
       this.sembuh2 = sembuh2;
       this.dirawat2 = dirawat2;
       this.meninggal2 = meninggal2;
    }
   
    public int getIdperubahan2() {
        return this.idperubahan2;
    }
    
    public void setIdperubahan2(int idperubahan2) {
        this.idperubahan2 = idperubahan2;
    }
    public String getWaktuperubahan2() {
        return this.waktuperubahan2;
    }
    
    public void setWaktuperubahan2(String waktuperubahan2) {
        this.waktuperubahan2 = waktuperubahan2;
    }
    public int getTerkonfirmasi2() {
        return this.terkonfirmasi2;
    }
    
    public void setTerkonfirmasi2(int terkonfirmasi2) {
        this.terkonfirmasi2 = terkonfirmasi2;
    }
    public int getSembuh2() {
        return this.sembuh2;
    }
    
    public void setSembuh2(int sembuh2) {
        this.sembuh2 = sembuh2;
    }
    public int getDirawat2() {
        return this.dirawat2;
    }
    
    public void setDirawat2(int dirawat2) {
        this.dirawat2 = dirawat2;
    }
    public int getMeninggal2() {
        return this.meninggal2;
    }
    
    public void setMeninggal2(int meninggal2) {
        this.meninggal2 = meninggal2;
    }




}


